// Generated by CoffeeScript 1.7.1
var linkSpase, request;

linkSpase = {
  link: {
    recent: []
  },
  num: "",
  album: ""
};

$(window).resize(function() {
  resizeRecent();
  return positionViewport();
});

$(document).keydown(function() {
  if ((e.which === 37) || (e.keyCode === 37)) {
    prePhoto();
  }
  if ((e.which === 39) || (e.keyCode === 39)) {
    return nextPhoto();
  }
});

request = {
  service: function() {
    return request.getJson("firstQuery", function(result) {
      request.album(result.collections["album-list"].href);
      return request.recent(result.collections["photo-list"].href);
    });
  },
  recent: function(setUrl) {
    return request.getJson(setUrl + "?format=json", function(result) {
      _.each(_.first(result.entries, 15), function(obj) {
        return linkSpase.link.recent.push(obj.img.XXXL.href);
      });
      return $('#content_recent').fadeIn(400);
    });
  },
  album: function(setUrl) {
    return request.getJson(setUrl + "?format=json", function(result) {
      return _.each(result.entries, function(obj) {
        return request.getLinkPhotos(obj.links.photos);
      });
    });
  },
  getLinkPhotos: function(setUrl) {
    return request.getJson(setUrl, function(result) {
      linkSpase.link[result.title] = [];
      return _.each(result.entries, function(obj) {
        return linkSpase.link[result.title].push(obj.img.XXXL.href);
      });
    });
  },
  getJson: function(setUrl, callback) {
    return $.ajax({
      type: "GET",
      url: "phpQuery/proxy.php",
      dataType: "json",
      data: {
        url: setUrl
      },
      success: function(data) {
        return callback(data);
      },
      error: function(err) {
        return alert('error');
      }
    });
  }
};

request.service();
