// Generated by CoffeeScript 1.7.1
var DisplayPhoto, linkSpase, positionPhotos, positionViewport, request, resizeRecent, _templ;

linkSpase = {
  link: {
    recent: []
  },
  num: "",
  album: ""
};

_templ = function(pattern, object) {
  var result, _template;
  _template = Handlebars.compile($(pattern).html());
  return result = _template(object);
};

positionViewport = function() {
  return $("#viewport").height($("#maxphoto").height());
};

resizeRecent = function() {
  $("#content_recent.content .blockCenter .contentPhoto").height($(window).height() - 140);
  return DeveloperTool.Init().ReloadAllCSSThisPage();
};

DisplayPhoto = function(album_name) {
  _.each(linkSpase.link[album_name], function(linkPhoto) {
    return $('#content_' + album_name + ' .blockCenter').append(_templ('#addPhoto-template', {
      page: album_name,
      link: linkPhoto
    }));
  });
  return resizeRecent();
};

positionPhotos = function(link) {
  console.log(link);
  $(".photo_hide_" + link).each(function() {
    if ($(this).width() > $(this).height()) {
      return $(this).addClass("horizontalPozitionImg");
    } else {
      return $(this).addClass("verticalPozitionImg");
    }
  });
  return bindEvent(link);
};

request = {
  getJson: function(setUrl, callback) {
    return $.ajax({
      type: "GET",
      url: "phpQuery/proxy.php",
      dataType: "json",
      data: {
        url: setUrl
      },
      success: function(data) {
        return callback(data);
      },
      error: function(err) {
        return alert('error');
      }
    });
  },
  getLinkPhotos: function(setUrl) {
    return request.getJson(setUrl, function(result) {
      linkSpase.link[result.title] = [];
      _.each(result.entries, function(obj) {
        return linkSpase.link[result.title].push(obj.img.XXXL.href);
      });
      return DisplayPhoto(result.title);
    });
  },
  album: function(setUrl) {
    return request.getJson(setUrl + "?format=json", function(result) {
      return _.each(result.entries, function(obj) {
        return request.getLinkPhotos(obj.links.photos);
      });
    });
  },
  recent: function(setUrl) {
    return request.getJson(setUrl + "?format=json", function(result) {
      _.each(_.first(result.entries, 15), function(obj) {
        return linkSpase.link.recent.push(obj.img.XXXL.href);
      });
      $('#content_recent').fadeIn(1000);
      return DisplayPhoto('recent');
    });
  },
  service: function() {
    return request.getJson("firstQuery", function(result) {
      request.album(result.collections["album-list"].href);
      return request.recent(result.collections["photo-list"].href);
    });
  }
};

$(document).ready(function() {
  return $(".link a").on({
    click: function() {
      var link;
      link = $(this).parent().attr("id");
      $('.content').fadeOut(400);
      return setTimeout(function() {
        $('#content_' + link).fadeIn(400);
        if (link !== "recent") {
          return positionPhotos(link);
        } else {
          return resizeRecent();
        }
      }, 400);
    }
  });
});

request.service();

resizeRecent();

$(window).resize(function() {
  return resizeRecent();
});
